import React from "react";
import {
  Phone, MessageCircle, Clock, Mail, FileText, Cog,
  Car, Bike, Wrench, KeyRound, PlugZap, Headset,
  Users, HeartHandshake, PackageCheck, PhoneCall, ReceiptText, Truck,
  Check, ArrowRight, MapPin, ChevronLeft, ChevronRight,
  PackageSearch, Timer, Handshake, ShieldCheck, Cookie,
  Menu, X, Facebook, Instagram, Linkedin, ArrowUp,
  LogIn, LogOut, UserPlus, Store, ChevronDown, ChevronUp, ShoppingCart,
  Save, Pencil, Plus, Minus, Trash2, ImagePlus, RefreshCw,
  AlertCircle, CheckCircle2, Lock, Building2, History, Download,
  ExternalLink, Search, Tag, Megaphone, Bell, Info, TriangleAlert, Paperclip,
  Copy, Link2, Link2Off,
} from "lucide-react";

/* Lucide icons keyed by the kebab-case names used across the kit. */
const ICONS = {
  phone: Phone,
  "message-circle": MessageCircle,
  clock: Clock,
  mail: Mail,
  "file-text": FileText,
  cog: Cog,
  car: Car,
  bike: Bike,
  wrench: Wrench,
  "key-round": KeyRound,
  copy: Copy,
  link: Link2,
  unlink: Link2Off,
  "plug-zap": PlugZap,
  headset: Headset,
  users: Users,
  "heart-handshake": HeartHandshake,
  "package-check": PackageCheck,
  "phone-call": PhoneCall,
  "receipt-text": ReceiptText,
  truck: Truck,
  check: Check,
  "arrow-right": ArrowRight,
  "map-pin": MapPin,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "package-search": PackageSearch,
  timer: Timer,
  handshake: Handshake,
  "shield-check": ShieldCheck,
  cookie: Cookie,
  menu: Menu,
  x: X,
  facebook: Facebook,
  instagram: Instagram,
  linkedin: Linkedin,
  "arrow-up": ArrowUp,
  "log-in": LogIn,
  "log-out": LogOut,
  "user-plus": UserPlus,
  store: Store,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "shopping-cart": ShoppingCart,
  save: Save,
  pencil: Pencil,
  plus: Plus,
  minus: Minus,
  "trash-2": Trash2,
  "image-plus": ImagePlus,
  "refresh-cw": RefreshCw,
  "alert-circle": AlertCircle,
  "check-circle-2": CheckCircle2,
  lock: Lock,
  "building-2": Building2,
  history: History,
  download: Download,
  "external-link": ExternalLink,
  search: Search,
  tag: Tag,
  megaphone: Megaphone,
  bell: Bell,
  info: Info,
  "triangle-alert": TriangleAlert,
  paperclip: Paperclip,
};

export function Icon({ name, size = 18, color = "currentColor", strokeWidth = 2 }) {
  const C = ICONS[name];
  if (!C) return null;
  return (
    <span style={{ display: "inline-flex", lineHeight: 0 }}>
      <C size={size} color={color} strokeWidth={strokeWidth} />
    </span>
  );
}
